config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/*
  get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker
  get "manifest" => "rails/pwa#manifest", as: :pwa_manifest

  resources :projects do
    get "activity_feed", to: "activity_feeds#show"
  end

   # Defines the root path route ("/")
   root "projects#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/event.rb
class Event < ApplicationRecord
  belongs_to :user
end

app/models/project.rb
class Project < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
end

app/controllers/activity_feeds_controller.rb
class ActivityFeedsController < ApplicationController
  def show
    @project = Project.find(params[:project_id])
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Only allow modern browsers supporting webp images, web push, badges, import maps, CSS nesting, and CSS :has.
  allow_browser versions: :modern
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  def index
    @projects = Project.all
  end

  def show
    @project = Project.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/activity_feeds/show.html.erb
<h1>Project #<%= @project.id %>Activity Feed</h1>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for(:title) || "Feedr" %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= yield :head %>

    <link rel="manifest" href="/manifest.json">
    <link rel="icon" href="/icon.png" type="image/png">
    <link rel="icon" href="/icon.svg" type="image/svg+xml">
    <link rel="apple-touch-icon" href="/icon.png">
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/projects/_project.html.erb
<div style="border: 1px solid black; margin-bottom: 2em; padding: 1em;">
  <h2><%= link_to "Project #{project.id}", project %></h2>
  <p><%= project.status %></p>
</div>

app/views/projects/index.html.erb
<h1>Projects</h1>

<%= render @projects %>

app/views/projects/show.html.erb
<h1>Project #<%= @project.id %></h1>
<p>Status: <%= @project.status %></p>
<%= link_to "Activity Feed", project_activity_feed_path(@project) %>